services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: besu
      POSTGRES_PASSWORD: besu
      POSTGRES_DB: besu
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
      - ./scripts/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@email.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8000:8080"
    volumes:
      - ./data/pgadmin/servers.json:/pgadmin4/servers.json
